# Generated by Django 4.2.12 on 2024-05-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoProject", "0002_consumer_account_consumer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DjangoProject.consumer"
            ),
        ),
    ]
