# Generated by Django 4.2.12 on 2024-05-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoProject", "0003_alter_account_consumer"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
