# Generated by Django 4.2.12 on 2024-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoProject", "0004_consumer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
